language: java
sudo: required
dist: trusty
install: true

services:
  - docker
  
jdk:
- oraclejdk8

before_script:
- ./gradlew composeUp


script:
- ./gradlew check





cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"

